name: ".NET Restore"

description: "Restore .NET dependencies for a project"

inputs:
    dotnet-version:
        description: '.NET version'
        required: true
        default: '9.x.x'
    project-directory:
        description: 'Path to project directory'
        required: true

runs:
    using: "composite"
    steps:
        - name: Checkout repository
          uses: actions/checkout@v5
          with:
            clean: true

        - name: Install .NET Core SDK
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: ${{ inputs.dotnet-version}}

        - name: Restore dependencies
          run: dotnet restore ${{ inputs.project-directory }} --no-cache
          shell: bash